<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_hero',
		'title' => 'Hero Details',
		'fields' => array (
			array (
				'key' => 'field_555ed065c0b90',
				'label' => 'Hero title',
				'name' => 'hero_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555ed085c0b91',
				'label' => 'Hero Blurb',
				'name' => 'hero_blurb',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'newsletters',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));

register_field_group(array (
		'id' => 'acf_book-details',
		'title' => 'Book Details',
		'fields' => array (
			array (
				'key' => 'field_555435d3db56a',
				'label' => 'Book',
				'name' => 'book',
				'type' => 'repeater',
				'required' => 1,
				'sub_fields' => array (
						array (
						'key' => 'field_555435dddb56b',
						'label' => 'Book Title',
						'name' => 'book_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_555435e8db56c',
						'label' => 'Book Cover',
						'name' => 'book_cover',
						'type' => 'image',
						'required' => 1,
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_5554360ddb56d',
						'label' => 'Author Name',
						'name' => 'author_name',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_55543615db56e',
						'label' => 'Book Price',
						'name' => 'book_price',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_55543615db56eorig',
						'label' => 'Original Price',
						'name' => 'book_original_price',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_55543621db56f',
						'label' => 'Book Blurb',
						'name' => 'book_blurb',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'br',
					),
					array (
						'key' => 'field_55543634db570',
						'label' => 'Book Category',
						'name' => 'book_category',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'Action Adventure' => 'Action Adventure',
							'Biography' => 'Biography',
							'Business' => 'Business',
							'Chicklit' => 'Chicklit',
							'Children\'s' => 'Children\'s',
							'Christian Living' => 'Christian Living',
							'Coming Of Age' => 'Coming Of Age',
							'Contemporary Romance' => 'Contemporary Romance',
							'Contemporary Women\'s Fiction' => 'Contemporary Women\'s Fiction',
							'Creative Writing' => 'Creative Writing',
							'Erotica' => 'Erotica',
							'Fantasy' => 'Fantasy',
							'Fiction' => 'Fiction',
							'Food' => 'Food',
							'Health and Medicine' => 'Health and Medicine',
							'Healthy Living' => 'Healthy Living',
							'Historical Fiction' => 'Historical Fiction',
							'Historical Romance' => 'Historical Romance',
							'Horror' => 'Horror',
							'Humor' => 'Humor',
							'Law' => 'Law',
							'LGBT' => 'LGBT',
							'Literary Fiction' => 'Literary Fiction',
							'Memoir' => 'Memoir',
							'Mid-Grade' => 'Mid-Grade',
							'Mystery' => 'Mystery',
							'New Adult' => 'New Adult',
							'Non-Fiction' => 'Non-Fiction',
							'Paranormal' => 'Paranormal',
							'Paranormal Romance' => 'Paranormal Romance',
							'Plays' => 'Plays',
							'Poetry' => 'Poetry',
							'Psychology' => 'Psychology',
							'Religion' => 'Religion',
							'Romance' => 'Romance',
							'Romantic Suspense' => 'Romantic Suspense',
							'Self Help' => 'Self Help',
							'Science Fiction' => 'Science Fiction',
							'Short Stories' => 'Short Stories',
							'Spirituality' => 'Spirituality',
							'Thriller' => 'Thriller',
							'Urban Fantasy' => 'Urban Fantasy',
							'Women\'s Contemporary Fiction' => 'Women\'s Contemporary Fiction',
							'Young Adult' => 'Young Adult',
							'Young Adult Fantasy' => 'Young Adult Fantasy',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
					array (
						'key' => 'field_55543656db571',
						'label' => 'Amazon ASIN',
						'name' => 'amazon_asin',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5554366cdb572',
						'label' => 'Barnes & Noble URL',
						'name' => 'barnes_noble_url',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_55543685db573',
						'label' => 'iBook URL',
						'name' => 'ibook_url',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_561ff9ecfca78',
						'label' => 'Lower Price',
						'name' => 'lower_price',
						'type' => 'checkbox',
						'choices' => array (
							'Yes' => 'Yes',
						),
						'default_value' => '',
						'layout' => 'horizontal',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'newsletters',
					'order_no' => 2,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));

	register_field_group(array (
		'id' => 'acf_cta-1',
		'title' => 'Call To Action 1',
		'fields' => array (
			array (
				'key' => 'field_555811c75bb3a',
				'label' => 'CTA Title 1',
				'name' => 'cta_title_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555811db5bb3b',
				'label' => 'CTA Blurb 1',
				'name' => 'cta_blurb_1',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_555ed09dc0b92',
				'label' => 'CTA Image 1',
				'name' => 'cta_image_1',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_555811f15bb3c',
				'label' => 'CTA Link Text 1',
				'name' => 'cta_link_text_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555811fa5bb3d',
				'label' => 'CTA URL 1',
				'name' => 'cta_url_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'newsletters',
					'order_no' => 3,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));

	register_field_group(array (
		'id' => 'acf_cta-2',
		'title' => 'Call To Action 2',
		'fields' => array (
			array (
				'key' => 'field_555811c75bb3a2',
				'label' => 'CTA Title 2',
				'name' => 'cta_title_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555811db5bb3b2',
				'label' => 'CTA Blurb 2',
				'name' => 'cta_blurb_2',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_555ed09dc0b922',
				'label' => 'CTA Image 2',
				'name' => 'cta_image_2',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_555811f15bb3c2',
				'label' => 'CTA Link Text 2',
				'name' => 'cta_link_text_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555811fa5bb3d2',
				'label' => 'CTA URL 2',
				'name' => 'cta_url_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'newsletters',
					'order_no' => 4,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
